- hosts: localhost
  connection: local
  become: true

  pre_tasks:
    - name: update repositories with pacman -Syu
      community.general.pacman:
        update_cache: true
        upgrade: true

  tasks:
    - import_tasks: tasks/nvidia.yml
    - import_tasks: tasks/packages.yml
    - import_tasks: tasks/terminator.yml
      vars:
        username: paul
    - import_tasks: tasks/neovim.yml
      vars:
        username: paul
    - import_tasks: tasks/i3.yml
      vars:
        username: paul
    - import_tasks: tasks/brave.yml
      vars:
        username: paul
    - import_tasks: tasks/libvirt.yml
      vars:
        username: paul
    - import_tasks: tasks/pentesting.yml
