- name: Clone ASDF (no recursive submodules)
  become_user: "{{ username }}"
  ansible.builtin.git:
    repo: https://github.com/asdf-vm/asdf.git
    dest: "/home/{{ username }}/.asdf"
    version: "v0.18.0"
    recursive: yes

- name: Add ASDF init to .bashrc
  become_user: "{{ username }}"
  lineinfile:
    path: "/home/{{ username }}/.bashrc"
    line: "{{ item }}"
    insertafter: EOF
    create: yes
  with_items:
    - ". $HOME/.asdf/asdf.sh"
