- name: Ensure Go is installed (via pacman)
  become: true
  pacman:
    name: go
    state: present

- name: Ensure Go bin path is in .bashrc
  become_user: "{{ username }}"
  lineinfile:
    path: "/home/{{ username }}/.bashrc"
    line: 'export PATH="$HOME/go/bin:$PATH"'
    insertafter: EOF

- name: Install ASDF v0.18.0 using go install
  become_user: "{{ username }}"
  shell: go install github.com/asdf-vm/asdf/cmd/asdf@v0.18.0
  environment:
    PATH: "/usr/bin:/bin:/usr/local/bin:/home/{{ username }}/go/bin"

- name: Add ASDF init to .bashrc (Go version)
  become_user: "{{ username }}"
  lineinfile:
    path: "/home/{{ username }}/.bashrc"
    line: ". $HOME/.asdf/lib/asdf.sh"
    insertafter: EOF
    create: yes
