- name: Clone ASDF (no recursive submodules)
  become_user: "{{ username }}"
  ansible.builtin.git:
    repo: https://github.com/asdf-vm/asdf.git
    dest: "/home/{{ username }}/.asdf"
    version: "v0.18.0"
    update: yes
    force: yes
    recursive: no

- name: Checkout v0.18.0 tag explicitly
  become_user: "{{ username }}"
  command: git checkout v0.18.0
  args:
    chdir: "/home/{{ username }}/.asdf"

- name: Update ASDF submodules
  become_user: "{{ username }}"
  command: git submodule update --init --recursive
  args:
    chdir: "/home/{{ username }}/.asdf"

- name: Add ASDF init to .bashrc
  become_user: "{{ username }}"
  lineinfile:
    path: "/home/{{ username }}/.bashrc"
    line: "{{ item }}"
    insertafter: EOF
    create: yes
  with_items:
    - ". $HOME/.asdf/asdf.sh"
    - ". $HOME/.asdf/completions/asdf.bash"
