# - name: Clone ASDF (no recursive submodules)
#   become_user: "{{ username }}"
#   ansible.builtin.git:
#     repo: https://github.com/asdf-vm/asdf.git
#     dest: "/home/{{ username }}/.asdf"
#     version: "v0.18.0"
#     recursive: yes

- name: Install ASDF Go binary via go install
  become_user: "{{ username }}"
  environment:
    PATH: "/home/{{ username }}/go/bin:{{ ansible_env.PATH }}"
  shell: |
    go install github.com/asdf-vm/asdf/cmd/asdf@v0.18.0
