- name: Clone ASDF
  become_user: "{{ username }}"
  ansible.builtin.git:
    repo: https://github.com/asdf-vm/asdf.git
    dest: "/home/{{ username }}/.asdf"
    recursive: true

- name: Add ASDF init to .bashrc
  become_user: "{{ username }}"
  lineinfile:
    path: "/home/{{ username }}/.bashrc"
    line: "{{ item }}"
    insertafter: EOF
    create: yes
  with_items:
    - ". $HOME/.asdf/asdf.sh"
    - ". $HOME/.asdf/completions/asdf.bash"
