- name: Install go
  community.general.pacman:
    name: go
    state: present

- name: Install go-tools
  community.general.pacman:
    name: go-tools
    state: present

- name: Install python-docutils
  community.general.pacman:
    name: python-docutils
    state: present

- name: Install apparmor
  community.general.pacman:
    name: apparmor
    state: present

- name: Install squashfs-tools
  community.general.pacman:
    name: squashfs-tools
    state: present

- name: Install xfsprogs
  community.general.pacman:
    name: xfsprogs
    state: present

- name: Install autoconf-archive
  community.general.pacman:
    name: autoconf-archive
    state: present


- name: Create a directory for installing odd software
  become_user: "{{ username }}"
  ansible.builtin.file:
    path: "/home/{{ username }}/Installs"
    state: directory

- name: Load Snapd from Arch aur
  become_user: "{{ username }}"
  ansible.builtin.git:
    repo: https://aur.archlinux.org/snapd.git
    dest: "/home/{{ username }}/Installs/snapd"

- name: Run makepkg -si
  become_user: "{{ username }}"
  ansible.builtin.command:
    chdir: "/home/{{ username }}/Installs/snapd"
    cmd: /sbin/makepkg --syncdeps --noconfirm --needed --noprogressbar --install
    creates: /var/lib/snapd/snap

- name: Enable Snapd
  ansible.builtin.systemd_service:
    state: started
    name: snapd.socket

- name: Install brave using snap
  community.general.snap:
    name:
      brave
