- name: Load Doom Emacs from Github
  become_user: "{{ username }}"
  ansible.builtin.git:
    repo: https://github.com/doomemacs/doomemacs
    dest: "/home/{{ username }}/.config/emacs"
    depth: 1
    branch: master
    update: yes

- name: Run Doom Emacs install
  become_user: "{{ username }}"
  ansible.builtin.command: "/home/{{ username }}/.config/emacs/bin/doom install --force"
  args:
    creates: "/home/{{ username }}/.config/emacs/.local"
