- name: Make sure we have the folder for odd installs
  become_user: "{{ username }}"
  ansible.builtin.file:
    path: "/home/{{ username }}/Installs"
    state: directory

- name: Load Flutter source from git
  become_user: "{{ username }}"
  ansible.builtin.git:
    repo: https://github.com/flutter/flutter.git
    dest: "/home/{{ username }}/Installs/flutter"
