- name: Install Picom Compositor for X
  community.general.pacman:
    name: picom
    state: present

- name: Install Nitrogen for background wallpaper managment
  community.general.pacman:
    name: nitrogen
    state: present

- name: Make sure flameshot is installed for screen capture
  community.general.pacman:
    name: flameshot
    state: present

- name: Install Icon Theme for rofi icons 
  community.general.pacman:
    name: papirus-icon-theme
    state: present

- name: Install Rofi for i3 program selecting
  community.general.pacman:
    name: rofi
    state: present

- name: Load my i3 config from Github
  become_user: "{{ username }}"
  ansible.builtin.git:
    repo: https://github.com/thegingerninja/i3_conf
    dest: "/home/{{ username }}/.config/i3"

- name: Create a directory for background images
  ansible.builtin.file:
    path: "/home/{{ username }}/Images/Backgrounds"
    state: directory
    mode: '0755'
