- name: Install necessary packages for Libvirt install
  community.general.pacman:
    name: [ 'qemu', 'virt-manager', 'dnsmasq', 'dmidecode', 'vde2', 'bridge-utils' ]
    state: present

- name: Install extra virtio drivers
  community.general.pacman:
    name: [ 'qemu-hw-display-virtio-gpu', 'qemu-hw-display-virtio-gpu-gl', 'qemu-hw-display-virtio-gpu-pci', 'qemu-hw-display-virtio-gpu-pci-gl', 'qemu-guest-agent', 'qemu-hw-usb-redirect', 'qemu-hw-display-qxl']
    state: present
    
- name: Install spice qemu drivers
  community.general.pacman:
    name: [ 'qemu-audio-spice', 'qemu-chardev-spice', 'qemu-ui-spice-app', 'spice-vdagent', 'spice', 'qemu-ui-spice-core', 'qemu-ui-spice-app' ]
    state: present
    
- name: Configure libvirt unix_sock_group
  ansible.builtin.lineinfile:
    path: /etc/libvirt/libvirtd.conf
    regexp: '^#\\s*unix_sock_group = .*$'
    line: 'unix_sock_group = "libvirt"'

- name: Configure libvirt unix_sock_rw_perms
  ansible.builtin.lineinfile:
    path: /etc/libvirt/libvirtd.conf
    regexp: '^#\\s*unix_sock_rw_perms = .*$'
    line: 'unix_sock_rw_perms = "0770"'

- name: Make sure the libvirt group exists
  ansible.builtin.group:
    name: libvirt
    state: present

- name: Add user to the libvirt group
  ansible.builtin.user:
    name: "{{ username }}"
    groups: libvirt
    append: yes
  
- name: Enable libvirtd Service
  ansible.builtin.systemd_service:
    name: libvirtd
    state: started
    enabled: yes
 
