- name: Install the Neovim package
  community.general.pacman:
    name: neovim
    state: present

- name: Load my Neovim config from Github
  become_user: "{{ username }}"
  ansible.builtin.git:
    repo: https://github.com/thegingerninja/lazy-nvim-conf
    dest: "/home/{{ username }}/.config/nvim"
