- name: Create snap symbolic link
  file:
    src: /snap
    dest: /var/lib/snapd/snap
    state: link
    force: yes

- name: Install VSCode using snap --classic
  community.general.snap:
    name: code
    classic: yes
