- name: Create snap symbolic link
  file:
    src: /var/lib/snapd/snap
    dest: /snap
    state: link
    force: yes

- name: Install VSCode using snap --classic
  community.general.snap:
    name: code
    classic: yes

- name: Install Android Studio using snap --classic
  community.general.snap:
    name: android-studio
    classic: yes
