- name: Install Terminator terminal
  community.general.pacman:
    name: terminator
    state: present

- name: Load Terminator config from git repo
  become_user: "{{ username }}"
  ansible.builtin.git:
    repo: https://github.com/thegingerninja/terminator_conf
    dest: "/home/{{ username }}/.config/terminator"

- name: Change the users shell to fish
  ansible.builtin.user:
    name: "{{ username }}"
    shell: /sbin/fish
