- name: Install necessary packages for VirtualBox install
  community.general.pacman:
    name: [ 'virtualbox', 'virtualbox-guest-iso' ]
    state: present

- name: Make sure the vboxusers group exists
  ansible.builtin.group:
    name: vboxusers
    state: present

- name: Add user to the vboxusers group
  ansible.builtin.user:
    name: "{{ username }}"
    groups: vboxusers
    append: yes

- name: Enable vboxweb Service
  ansible.builtin.systemd_service:
    name: vboxweb
    state: started
    enabled: yes
    
